export {default as Mymessage} from "./friends/friends"
export {default as Mypost} from "./post/post"
export {default as Search} from "./searchbar/searchbar"
export {default as Myprofile} from "./profile/profile"
export {default as loginput} from "./login/login"
export {default as butlogin} from "./button li/button"
export {default as butregister} from "./button re/button"
export {default as reginput} from "./register/register"
export {default as butlanding} from "./button landing/button landing"
export {default as Myeditarprofile} from "./editar perfil/editar perfil"
export {default as Listregister} from "./listregister/listregister"
export {default as listlogin} from "./listlogin/listlogin"