export {default as Mymessage} from "./message/message"
export {default as Mypost} from "./post/post"
export {default as Search} from "./searchbar/searchbar"
export {default as Myprofile} from "./profile/profile"
export {default as loginput} from "./login/login"
export {default as butlogin} from "./button li/button"